### ISSUE TITLE
兄弟，代码好像没传上来，就一个main.dart

### ISSUE THREAD

**Issue by xiongdi9456** [424626154/flutter_sudoku#2]
如题

**Comment by 424626154** [comment]
@xiongdi9456   这是一个悲伤的故事，那晚在硬盘空间不足的情况下，竟然误删了源代码！后边我会抽时间重写下。

**Comment by xiongdi9456** [comment]
@424626154 没什么比这个还郁闷，我之前电脑坏了一次吓死我，从那以后老老实实git。兄弟，做好了可以合作，前端都交给你，发海外，赚点外快
